"""Prompt templates for the article-generation strategies.

Namespaced by strategy: ``REPORT_*`` (baseline), ``GINGER_*`` (ginger), ``QA_*``
(qa). The ``bullet`` pipeline uses the note-taking prompt *builders* at the end
of this module. Each module imports what it needs from here.
"""

from collections.abc import Sequence

# Shared prompt helpers stay in marquis.common.prompts (generic infra).
from marquis.common.prompts import _format_optional_json_block, _retry_wrapper, _strict_json_tail

# baseline

REPORT_PROMPT = """You are a report writing assistant. Your task is to synthesize a set of claims extracted from multiple videos into a single, fluent, well-organized report that answers the given query.

## Instructions:
1. Read all the claims below carefully. Each claim was extracted from a specific video and has a timestamp.
2. Group related claims together logically (e.g., by sub-topic or chronological order).
3. Write a coherent, well-structured report that covers all the key information from the claims.
4. For EVERY piece of information in your report, include an inline citation in the format [video_id, timestamp_start-timestamp_end].
5. If multiple claims from different videos support the same point, cite all relevant sources.
6. Remove redundant information — if multiple claims say the same thing, mention it once and cite all sources.
7. The report should be fluent and readable, not a list of bullet points.
8. Keep the report concise but comprehensive (aim for 200-400 words).

## Query/Topic: {topic}

## Claims:
{claims_text}

## Report:
"""


# ginger

GINGER_CLUSTER_PROMPT = """You are an information analyst. Given a set of claims about a topic extracted from videos, group them into distinct facet clusters. Each cluster should represent a different sub-topic or aspect of the main topic.

## Instructions:
1. Read all claims carefully.
2. Group them into clusters based on their sub-topic/facet (e.g., "casualties", "rescue efforts", "damage assessment", "government response", etc.).
3. Each claim should belong to exactly one cluster.
4. Give each cluster a short, descriptive label.
5. Output your result as a JSON object with the following format:

```json
{{
  "clusters": [
    {{
      "label": "Short descriptive label for this facet",
      "claim_ids": ["qc-10-xxx-000", "qc-10-xxx-001"]
    }},
    ...
  ]
}}
```

Only output the JSON object, no other text.

## Topic: {topic}

## Claims:
{claims_text}
"""

GINGER_RANK_PROMPT = """You are a relevance assessor. Given a query/topic and a list of facet clusters (each containing grouped claims from videos), rank the clusters from most to least relevant to the query.

## Instructions:
1. Consider which facets are most important for answering/addressing the query topic.
2. Rank all clusters from most relevant to least relevant.
3. Output a JSON array of cluster labels in order from most to least relevant:

```json
{{
  "ranked_labels": ["most relevant label", "second most relevant", ...]
}}
```

Only output the JSON object, no other text.

## Topic: {topic}

## Clusters:
{clusters_text}
"""

GINGER_SUMMARIZE_PROMPT = """You are a concise summarizer. Summarize the following cluster of claims into a SINGLE sentence (maximum 40 words). The sentence must:
1. Capture the key information from all claims in this cluster.
2. Include inline citations in the format [video_id, timestamp] for every fact mentioned.
3. Be factual — only include information present in the claims.

## Cluster: {cluster_label}

## Claims in this cluster:
{cluster_claims_text}

## One-sentence summary:
"""

GINGER_FLUENCY_PROMPT = """You are an editor. Below is a report composed of individual summary sentences about the topic "{topic}". Your task is to rewrite it into a smooth, fluent, well-organized report.

## Rules:
1. Do NOT add any new information that is not in the summaries below.
2. Do NOT remove any information or citations from the summaries.
3. Keep ALL inline citations in the format [video_id, timestamp].
4. Improve transitions between sentences for better readability.
5. You may reorder sentences for better logical flow.
6. Keep the report concise (200-400 words).

## Draft report (concatenated summaries):
{draft_report}

## Final polished report:
"""


# qa

QA_BASELINE_PROMPT = """You are a report writing assistant. Your task is to synthesize a set of question-answer pairs (extracted by a QA system from video sources) into a single, fluent, well-organized report that answers the user's original query.

## Instructions:
1. Read all the Q&A pairs below carefully. Each answer was generated by a QA system using specific video sources.
2. Synthesize the answers into a coherent, well-structured report.
3. For EVERY piece of information in your report, include an inline citation listing the source videos in the format [video_id].
4. If an answer says "I don't know" or lacks information, skip it.
5. Remove redundant information across answers — mention key facts once and cite all relevant sources.
6. The report should be fluent and readable, not a list of Q&A.
7. Keep the report concise but comprehensive (aim for 200-400 words).

## User's original query: {query}

## Q&A pairs from videos:
{qa_text}

## Report:
"""

QA_CLUSTER_PROMPT = """You are an information analyst. Given a set of Q&A pairs about a topic extracted from videos, group them into distinct facet clusters based on sub-topic/aspect.

## Instructions:
1. Read all Q&A pairs carefully.
2. Group them into clusters by sub-topic.
3. SKIP Q&A pairs where the answer is "I don't know" or has no useful information.
4. Each pair should belong to exactly one cluster.
5. Output as JSON:

```json
{{
  "clusters": [
    {{
      "label": "Short descriptive label",
      "qa_ids": [0, 1, 3]
    }}
  ]
}}
```

Only output the JSON object, no other text.

## Topic: {query}

## Q&A pairs (each prefixed with its ID):
{qa_text}
"""

QA_RANK_PROMPT = """Given a query and facet clusters of Q&A pairs, rank clusters from most to least relevant.

Output as JSON:
```json
{{
  "ranked_labels": ["most relevant label", "second most relevant", ...]
}}
```

Only output the JSON object.

## Query: {query}

## Clusters:
{clusters_text}
"""

QA_SUMMARIZE_PROMPT = """Summarize the following cluster of Q&A pairs into a SINGLE sentence (maximum 45 words). Rules:
1. Capture the key information from all answers.
2. Include inline citations [video_id] for every fact.
3. Only include information actually present in the answers.

## Cluster: {cluster_label}

## Q&A pairs:
{cluster_qa_text}

## One-sentence summary:
"""

QA_FLUENCY_PROMPT = """Rewrite the following draft into a smooth, fluent report about: "{query}"

## Rules:
1. Do NOT add new information or remove citations.
2. Keep ALL inline [video_id] citations.
3. Improve transitions and flow.
4. Keep concise (200-400 words).

## Draft:
{draft_report}

## Polished report:
"""


# bullet (note-taking infer → annotate) prompt builders


def prompt_higher_level_inference(
    *,
    query_id: str,
    query: str,
    topic: str,
    evidence_items: Sequence[dict],
) -> str:
    expected_shape = {
        "inferences": [
            {
                "claim": "...",
                "source_ids": ["id-1", "id-2", "id-3"],
            }
        ]
    }
    parts = [
        "You are synthesizing higher-level inferences from evidence items for a query.",
        "",
        "Query context:",
        f"- query_id: {query_id}",
        f"- topic: {topic}",
        f"- query: {query}",
        "",
        _format_optional_json_block("Evidence items", list(evidence_items)),
        "",
        "Rules:",
        "- Synthesize higher-level claims that integrate multiple evidence items.",
        "- Every inference must cite its supporting evidence via source_ids.",
        "- Do not fabricate information beyond what the evidence supports.",
        "- If the evidence is insufficient for any inference, return an empty inferences list.",
        "- Avoid duplicating evidence items verbatim as inferences.",
    ]
    return "\n".join(parts) + _strict_json_tail(expected_shape)


def prompt_higher_level_inference_retry(
    *,
    query_id: str,
    query: str,
    topic: str,
    evidence_items: Sequence[dict],
) -> str:
    return _retry_wrapper(
        prompt_higher_level_inference(
            query_id=query_id,
            query=query,
            topic=topic,
            evidence_items=evidence_items,
        ),
        {
            "inferences": [
                {
                    "claim": "...",
                    "source_ids": ["id-1", "id-2", "id-3"],
                }
            ]
        },
    )


def prompt_annotate_citations(
    *,
    text: str,
    sources: list,
) -> str:
    """Prompt to insert inline [N] markers into a finding text."""
    source_lines = []
    for i, src in enumerate(sources, 1):
        vid = src.get("video_id", "?")
        ts = src.get("timestamp")
        ts_str = f"{ts[0]:.0f}s-{ts[1]:.0f}s" if ts else "N/A"
        claim = src.get("claim", "")
        source_lines.append(f"[{i}] video:{vid} {ts_str} | {claim}")

    expected_shape = {"annotated_text": "...fact A[1], while fact B[2]..."}
    parts = [
        "You are inserting inline citations into a finding text.",
        "",
        f'Finding: "{text}"',
        "",
        "Sources:",
        *source_lines,
        "",
        "Rules:",
        "- Insert [N] immediately after the specific phrase that source N supports.",
        "- If a source jointly supports multiple phrases, insert [N] after each relevant phrase.",
        "- Every source number [N] must appear at least once in the annotated text.",
        "- Do NOT change any wording, only add [N] markers.",
    ]
    return "\n".join(parts) + _strict_json_tail(expected_shape)


def prompt_annotate_citations_retry(*, text: str, sources: list) -> str:
    return _retry_wrapper(
        prompt_annotate_citations(text=text, sources=sources),
        {"annotated_text": "...fact A[1], while fact B[2]..."},
    )
