defaults:
  - data: default
  - model: default
  - runtime: default
  - output: default
  - launcher: local
  - optional experiment: null
  - _self_

stage: retrieval

hydra:
  run:
    dir: .
  output_subdir: null
